server:
  servlet:
    encoding:
      force-response: true

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher


  application:
    name: sns-restapi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 1234

  jpa:

    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  issuer: kevin9160@naver.com
  secret-key: study-spring
  expireTimeMs: 600000


